
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Apr 25 14:43:47 PDT 2012
//----------------------------------------------------

package com.inductiveautomation.xopc.drivers.modbus2.address.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int LETTER = 3;
  public static final int BIT_SEPARATOR = 4;
  public static final int PERIOD = 6;
  public static final int STRING_SEPARATOR = 5;
  public static final int EOF = 0;
  public static final int DIGIT = 2;
}

