Shape.Smiley.Name=Smiley Face
Shape.Smiley.Category=Shape
Shape.Smiley.Description=Add a smiley face to your report.
Shape.Smiley.Background.Category=Color
Shape.Smiley.Background.Name=Background
Shape.Smiley.Foreground.Category=Color
Shape.Smiley.Foreground.Name=Foreground
Shape.Smiley.Happy.Category=Fun
Shape.Smiley.Happy.Name=Is Happy

Shape.RMSmiley.Name=Smiley Face
Shape.RMSmiley.Category=Shape
Shape.RMSmiley.Description=Add a smiley face to your report.
Shape.RMSmiley.Background.Category=Color
Shape.RMSmiley.Background.Name=Background
Shape.RMSmiley.Foreground.Category=Color
Shape.RMSmiley.Foreground.Name=Foreground
Shape.RMSmiley.Happy.Category=Fun
Shape.RMSmiley.Happy.Name=Is Happy